### ISSUE TITLE
Trying out craft-order-refunds

### ISSUE THREAD

**Issue by lsuprina** [yoannisj/craft-order-refunds#1]
Hello. I have an urgent problem with refunding and restocking line items. I found your comment on issue to add RMA functionality (https://github.com/craftcms/commerce/issues/1046). I read that you are releasing your plugin soon, but I would like to try it out ASAP if that is alright with you. I hope you can help me. Thank you.

**Comment by yoannisj** [comment]
hi @lsuprina , sure! I just answered to you in Craft CMS's discord channel!

**Comment by smonist** [comment]
@yoannisj [yoannisj](https://github.com/yoannisj) Would you mind posting you answer here? I can't find it anywhere on discord.
